FROM ubuntu:focal-20211006

RUN apt-get -y update
RUN apt-get install -y \
    python3 \
    pip \
    git

RUN pip install \
    numpy \
    astropy \
    numba \
    bottleneck \
    h5py \
    attrs \
    rich \
    click \
    iqrm

RUN python3 -m pip install -U git+https://github.com/FRBs/sigpyproc3
RUN apt-get install -y gcc
RUN git clone https://github.com/mitchmickaliger/pulsarTools.git
COPY ./install /pulsarTools
RUN make install
   


CMD /bin/bash